### ISSUE TITLE
Unable to login to Steam using username and password

### ISSUE THREAD

**Issue by jiajiaxd** [Gobot1234/steam.py#307]
### Summary

Unable to login to Steam

### Reproduction Steps

1. Attempt to login using the steam.login() function with shared_secret.
2. Receive a prompt for steam guard code even though shared_secret was provided.
3. Enter the steam guard code.
4. Observe that the program hangs indefinitely.

Here is the code snippet:
```
logger.info("正在登录...")
asyncio.run(
    client.login(
        acc.get("steam_username"),
        acc.get("steam_password"),
        shared_secret=acc.get("steam_shared_secret"),
        identity_secret=acc.get("steam_identity_secret"),
    )
)
```

### Expected Results

The program should login successfully without prompting for steam guard code when shared_secret is provided.

### Actual Results

The program prompts for steam guard code even with shared_secret and hangs indefinitely after entering the code.

### System Information

```
root@jiajiaxd-do-us-sf:~/Steamauto# python3 -m steam
python version: 3.10.12
steam.py version: 1.0.0a2898+g56e9ca3
aiohttp version: 3.8.5
betterproto version: 2.0.0b6
operating system info: Linux-5.15.120-bbrplus-x86_64-with-glibc2.35
```

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Gobot1234** [comment]
I've been looking into this but I'm not entirely sure what I can do, steam just doesn't appear to be sending the data after I disconnect from the CM the first time (required because otherwise you get InvalidPassword #274) looking at node-steam-user this shouldn't be required. If you want a fix for this just use the `refresh_token` that's generated when you login

**Comment by jiajiaxd** [comment]
May I ask how can I obtain the refresh_token...😣

**Comment by Gobot1234** [comment]
It's just an attribute on Client you should get after being connected to the CM and entering a code or you can get it from the steam logs. Also are you sure that `steam_shared_secret` is present in `acc`? because it seems to me like the only way you could be prompted for a code is if it's None

**Comment by jiajiaxd** [comment]
Sorry I have made a stupid mistake.I didn't check the code that copilot generated...But the problem of hanging indefinitely is still there.

**Comment by Gobot1234** [comment]
Well at the very least I can't figure out the issue, comparing it to DoctorMcKays implementation it seems the same and steam is the thing disconnecting me so I said it's a steam issue.

**Comment by NiceAesth** [comment]
At the moment logging in to accounts which have no steam guard set up hangs indefinitely. Is there any part that would be worth looking into?

**Comment by Gobot1234** [comment]
That sounds like the same issue I think, you just need to manually grab the refresh token from logs or the on_connect event (after a delay)

**Comment by mayacopeland** [comment]
From a glance, https://github.com/Gobot1234/steam.py/blob/336064153a1fea5c751a5c5f60a71c1afe4b0c7f/steam/client.py#L600 ONLY uses self.refresh_token or self.shared_secret, and seemingly ignores the username and password given?

**Comment by Gobot1234** [comment]
Your glance has lead you to forget that those attributes are assigned and can be accessed from anywhere.

**Comment by somespecialone** [comment]
@Gobot1234 , faced same issue. Find out that [this](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L436-L447)
```py
msg: login.CMsgClientLogonResponse = await self.send_proto_and_wait(
    login.CMsgClientLogon(
        protocol_version=PROTOCOL_VERSION,
        client_package_version=1561159470,
        client_os_type=16,
        client_language=state.language.api_name,
        supports_rate_limit_response=True,
        chat_mode=2,
        access_token=self.refresh_token,  # lol
    ),
    check=lambda msg: isinstance(msg, login.CMsgClientLogonResponse),
)
```
exceed [timeout](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/client.py#L488-L489)
```py
async with timeout(60):
    self.ws = cast(SteamWebSocket, await login_func(self, *args, **kwargs, cm_list=cm_list))
```
so steam never response, when in same time DoctorMcKay's `node-steam-user` work fine with same account. Not tested yet, but problem be in difference of proto's? To clarify, node lib send proto with different fields to server (I even not investigate values, can't decode protos somehow). For example, `steamid`, `client_sessionid ` from node's [CMsgProtoBufHeader](https://github.com/DoctorMcKay/node-steam-user/blob/a9e1d2be73760f881f214bd7dffc74fbc7311cc7/protobufs/steammessages_base.proto#L95-L96) and `steam_id`, `session_id` from steam.py's [CMsgProtoBufHeader class](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/protobufs/headers.py#L27-L28), and more. What do you think?

**Comment by Gobot1234** [comment]
Names aren't encoded in the protobuf, so unfortunately that's not it

**Comment by somespecialone** [comment]
@Gobot1234 is this intentional that we store `refresh_token` only on [SteamWebSocket](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L283) and not on client (there is a getter to ws)? This leads to next:
1. Attempt to get `refresh_token` if there is a none -> [this](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L429)
2. Attempt to send `ClientLogon` to new CM server to not get `InvalidPassword` as you mention before [there](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L436) where we exceed timeout (this need problem need investigation).
3. [Throttling](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/client.py#L493)
4. Return to step 1 without `resfresh_token`.
I mean we have infinite loop `throttle -> get refresh token -> exceed timeout sending ClientLogon`. So, question is may be this is uninetional? We lost refresh token with SteamWebSocket instance after each timeout exceed attempt, may be we need to preserve it and store, for example, on client [there](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L429-L431) after we fetch it?
 
BTW, this is not fix steam silence, but solve this issue as well.

**Comment by Gobot1234** [comment]
I appreciate all the effort you're putting into this,

I don't think only storing on `.ws` should be an issue because it should be using the refresh token that it fetched because AFAICT it should be setting the the refresh_token. If that isn't the case though then yes it's a bug.

**Comment by Gobot1234** [comment]
After looking into this a bit further myself I've noticed we are getting the right login response but the code still hangs and I'm not immediately sure why
```py
            async with self.poll():
                await self.send_proto(login.CMsgClientHello(PROTOCOL_VERSION))

                print("Logging in properly?", refresh_token)  # prints twice, once with None then with the refresh token as expected
                if refresh_token is None:
                    self.refresh_token = refresh_token = await self.fetch_refresh_token()
                    print("Setting refresh_token")
                    # id64 is set in fetch_refresh_token
                    continue  # steam doesn't seem to like when I login in straight away
                else:
                    self.refresh_token = refresh_token
                    self.id64 = parse_id64(utils.decode_jwt(refresh_token)["sub"])

                future = self.wait_for(login.CMsgClientLogonResponse)
                await self.send_proto(
                    login.CMsgClientLogon(
                        protocol_version=PROTOCOL_VERSION,
                        client_package_version=1561159470,
                        client_os_type=16,
                        client_language=state.language.api_name,
                        supports_rate_limit_response=True,
                        chat_mode=2,
                        access_token=self.refresh_token,  # lol
                    ),
                )
                print("Sent!")
                msg = await future
                print("Got response", msg)  # never gets past here
                if msg.result != Result.OK:
                    log.debug("Failed to login with result: %r", msg.result)
                    await self._state.handle_close()
```

**Comment by somespecialone** [comment]
Getting the right login response? Or I misunderstood you or we are not getting anything. Then I think problem is related to #274 , because in node's lib things just work in straight way: `send hello -> get refresh_token -> send logon -> recieve OK response`. I'll try to take a step back and see if I can find something.

**Comment by Gobot1234** [comment]
I can see the response in debug logs but its future doesn't seem to get set properly

**Comment by somespecialone** [comment]
> I can see the response in debug logs but its future doesn't seem to get set properly

It is because we recieve `KeyError` [right here](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L741):

```py
try:
    event_parser = self._state.parsers[msg.MSG]  # <- 
except (KeyError, TypeError):
    try:
        log.debug("Ignoring %r as unhandled event", msg)
    except Exception:
        log.debug("Ignoring %r as unhandled unparseable event", msg.__class__)
else:
```
For whatevere reason parsers dict not contain parser for `EMsg.ClientLogOnResponse`.  Can't give more details, not really deep into the lib code 🙂

**Comment by Gobot1234** [comment]
Those are for static handlers not just events that are currently being `wait_for`'ed so it's not that. I think there are multiple instances of SteamWebsocket but I haven't really looked into it recently, bit too busy.

**Comment by somespecialone** [comment]
Good news, @Gobot1234. I found issue with #274. You just forgot to set `id64` to ws when we fetch token [there](https://github.com/Gobot1234/steam.py/blob/aaa08e17da1e9356ececa29d0f240aaac87dd6fb/steam/gateway.py#L428-L434). 

This work as well:
```py
if refresh_token is None:
    self.refresh_token = refresh_token = await self.fetch_refresh_token()
    # id64 is set in fetch_refresh_token
    # continue  # steam doesn't seem to like when I login in straight away
else:
    self.refresh_token = refresh_token

self.id64 = parse_id64(utils.decode_jwt(refresh_token)["sub"])
```

**Comment by Gobot1234** [comment]
I love leaving comments that don't apply anymore, good catch thanks!
